Initial Xcode 4 template support.
To get it working, run ``rake install``. Then start a new project with the Wax choice. Click the project file at left, then go to "Build Settings". You'll need to manually set the "Product Name". Finally, at a shell, symlink the source ``wax`` checkout into the project.

It should mostly build, dying with something like "ld: symbol(s) not found for architecture i386".